### PR TITLE
Create tags for network-service actions so that

### PR DESCRIPTION
**Pull request by galthaus**
they can be controlled without knowing what the
network-service is.

### CODE REVIEW

**Comment by pedro-r-marques** [comment]
@galthaus merging in my fork... please submit upstream also.

**Comment by galthaus** [comment]
I'll attempt to.  One one of these is currently up stream.  :-)

**Comment by galthaus** [comment]
Upstream pull request: #275

**Comment by galthaus** [comment]
The real pull request is: #277

**Pull request merged**
